version: '3.9'

services:
  backend:
<<<<<<< HEAD
    # networks:
      # - project
=======
    networks:
      - project
>>>>>>> 43a047f (ajusted speeds)
    container_name: backend
    build:
      context: ./src/django/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
<<<<<<< HEAD
    # networks:
      # - project
=======
    networks:
      - project
>>>>>>> 43a047f (ajusted speeds)
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: boby
    # build:
    #   context: ./src/pgsql/Dockerfile
    #   dockerfile: Dockerfile

<<<<<<< HEAD
# networks:
#   project:
#     driver: bridge
=======
networks:
  project:
    driver: bridge
>>>>>>> 43a047f (ajusted speeds)

