version: '3.9'

services:
  backend:
    # networks:
      # - project
    container_name: backend
    build:
      context: ./src/django/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    # networks:
      # - project
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: boby
    # build:
    #   context: ./src/pgsql/Dockerfile
    #   dockerfile: Dockerfile
<<<<<<< HEAD
networks:
  project:
    driver: bridge
=======

# networks:
#   project:
#     driver: bridge
>>>>>>> f4f2346 (🚧 feat: Home page commence)

