version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./src/django/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: boby
    # build:
    #   context: ./src/pgsql/Dockerfile
    #   dockerfile: Dockerfile

