### Login request
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "stan4",
    "password": "Pass1234!"
}

### Signup request
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
    "username": "stan4",
    "password1": "Pass1234!",
    "password2": "Pass1234!"
}
###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token a18613695df0ff05a86762a8348c727a4f69dbd8

{
}

###

GET http://127.0.0.1:8000/register
Content-Type: application/json

{
}






# Authorization: token xxx
