### Login request
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "stan1",
    "password": "Pass1234!"
}

### Signup request
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "stan1",
    "password1": "Pass1234!",
    "password2": "Pass1234!"
}
###

GET http://localhost:8000/auth/test_token
Content-Type: application/json
Authorization: Token 8e7b4872b72641439fbdced35058a25c536a38a4

{
}

###

GET http://localhost:8000/auth/register
Content-Type: application/json

{
}

###

GET http://localhost:8000/auth/login
Content-Type: application/json

{
}





# Authorization: token xxx
