# Generated by Django 5.0.7 on 2024-07-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='stats',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
    ]
