# Generated by Django 5.0.7 on 2024-07-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_room_stats_delete_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='gamePlay',
            new_name='gamePlayed',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gameWin',
            new_name='gameWon',
        ),
    ]
