# Generated by Django 5.1.1 on 2024-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_gameplay_player_gameplayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stanid',
            field=models.IntegerField(default=0),
        ),
    ]
