# Generated by Django 5.1.1 on 2024-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.TextField(default=[]),
        ),
    ]
