# Generated by Django 5.1.1 on 2024-10-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_room_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
