# Generated by Django 5.1.1 on 2024-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playerCount',
            field=models.IntegerField(default=0),
        ),
    ]
