# Generated by Django 4.2.14 on 2024-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokubattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('difficulty', models.IntegerField()),
                ('board', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
