# Generated by Django 4.2 on 2024-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokubattle', '0003_myuser_alter_sudokuroom_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokuroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
