# Generated by Django 4.2 on 2024-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokubattle', '0005_alter_myuser_user_id_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokuroom',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
