# Generated by Django 4.2 on 2024-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokubattle', '0006_sudokuroom_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokuroom',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
    ]
