# Generated by Django 5.0.7 on 2024-07-27 13:02

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
