# Generated by Django 4.2 on 2024-08-12 15:23

import authapi.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0005_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sms',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. (e.g., +1234567890 or 1234567890)', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tfa',
            field=models.JSONField(default=authapi.models.default_preferences),
        ),
    ]
