# Generated by Django 4.2 on 2024-08-23 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sms',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. (e.g., +1234567890 or 1234567890)', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
