# Generated by Django 4.2 on 2024-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0009_alter_userprofile_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.png', null=True, upload_to='images/'),
        ),
    ]
