# Generated by Django 4.2 on 2024-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
