# Generated by Django 4.2 on 2024-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0013_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jwt',
            field=models.TextField(blank=True),
        ),
    ]
