# Generated by Django 4.2 on 2024-09-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0015_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_loss', to='authapi.userprofile'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to='authapi.userprofile'),
        ),
    ]
