# Generated by Django 4.2 on 2024-09-27 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0016_alter_gamehistory_loser_alter_gamehistory_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sms',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. (e.g., +1234567890 or 1234567890)', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
